version: '2'
services:
  ui:
    container_name: frontend
    build: ./ui
    ports:
      - '3000:3000'
    depends_on:
      - api
  api:
    container_name: backend
    build: ./api
    ports:
      - '8080:8080'
    depends_on:
      - mongo
  mongo:
    container_name: db
    image: mongo
    ports:
      - '27017:27017'